### ISSUE TITLE
스켈레톤 작성

### ISSUE THREAD

**Issue by csdany** [k9qivhda/calculator#1]
프로젝트를 시작하기 위한 스켈레톤을 작성합니다

- main() 함수

**Comment by csdany** [comment]
사칙연산을 담당하는 각각의 함수를 작성하는 것이 좋겠습니다.
예를 들면 
add(int a, int b)
sub(int a, int b)
...

**Comment by k9qivhda** [comment]
네, 저도 찬성입니다.
